import os 

# Read in the file
with open('assessment_nbhd.csv', 'r') as file :
  filedata = file.read()

# Replace the target string
filedata = filedata.replace('Old City 2', '1')
filedata = filedata.replace('Foggy Bottom', '2')
filedata = filedata.replace('Central-tri 1', '3')
filedata = filedata.replace('Old City 1', '4')
filedata = filedata.replace('Southwest Waterfront', '5')
filedata = filedata.replace('Capitol Hill', '6')
filedata = filedata.replace('Georgetown', '7')
filedata = filedata.replace('Glover Park', '8')
filedata = filedata.replace('Burleith', '9')
filedata = filedata.replace('Palisades', '10')
filedata = filedata.replace('Berkley', '11')
filedata = filedata.replace('Foxhall', '12')
filedata = filedata.replace('Kent', '13')
filedata = filedata.replace('Wesley Heights', '14')
filedata = filedata.replace('American University', '15')
filedata = filedata.replace('Spring Valley', '16')
filedata = filedata.replace('Chevy Chase', '17')
filedata = filedata.replace('North Cleveland Park', '18')
filedata = filedata.replace('Wakefield', '19')
filedata = filedata.replace('Cleveland Park', '20')
filedata = filedata.replace('Observatory Circle', '21')
filedata = filedata.replace('Forest Hills', '22')
filedata = filedata.replace('Massachusetts Avenue Heights', '23')
filedata = filedata.replace('Woodley', '24')
filedata = filedata.replace('Takoma Park', '25')
filedata = filedata.replace('Rock Creek Park', '26')
filedata = filedata.replace('Kalorama', '27')
filedata = filedata.replace('Garfield', '28')
filedata = filedata.replace('Hawthome', '29')
filedata = filedata.replace('Mt. Pleasant', '30')
filedata = filedata.replace('Crestwood', '31')
filedata = filedata.replace('Columbia Heights', '32')
filedata = filedata.replace('16th Street Heights', '33')
filedata = filedata.replace('Brightwood', '34')
filedata = filedata.replace('Shepherd Heights', '35')
filedata = filedata.replace('Colonial Village', '36')
filedata = filedata.replace('Petworth', '37')
filedata = filedata.replace('Ledroit Park', '38')
filedata = filedata.replace('Eckington', '39')
filedata = filedata.replace('Chillum', '40')
filedata = filedata.replace('Brookland', '41')
filedata = filedata.replace('Riggs Park', '42')
filedata = filedata.replace('Brentwood', '43')
filedata = filedata.replace('Trinidad', '44')
filedata = filedata.replace('Woodridge', '45')
filedata = filedata.replace('Michigan Park', '46')
filedata = filedata.replace('Fort Lincoln', '47')
filedata = filedata.replace('Lily Ponds', '48')
filedata = filedata.replace('Deanwood', '49')
filedata = filedata.replace('Marshall Heights', '50')
filedata = filedata.replace('Fort Dupont Park', '51')
filedata = filedata.replace('Hillcrest', '52')
filedata = filedata.replace('Anacostia', '53')
filedata = filedata.replace('Randle Heights', '54')
filedata = filedata.replace('Barry Farms', '55')
filedata = filedata.replace('Congress Heights', '56')
filedata = filedata.replace('Central-tri 3', '57')


# Write the file out again
with open('assessment_nbhd.csv', 'w') as file:
  file.write(filedata)


