import os 

# Read in the file
with open('assubnbhd.csv', 'r') as file :
  filedata = file.read()

# Replace the target string
filedata = filedata.replace('040 D Old City 2', '1')
filedata = filedata.replace('040 E Old City 2', '2')
filedata = filedata.replace('040 C Old City 2', '3')
filedata = filedata.replace('040 F Old City 2', '4')
filedata = filedata.replace('040 G Old City 2', '5')
filedata = filedata.replace('040 B Old City 2', '6')
filedata = filedata.replace('040 A Old City 2', '7')
filedata = filedata.replace('039 E Old City 1', '8')
filedata = filedata.replace('009 C Capitol Hill', '9')
filedata = filedata.replace('009 A Capitol Hill', '10')
filedata = filedata.replace('039 J Old City 1', '11')
filedata = filedata.replace('039 K Old City 1', '12')
filedata = filedata.replace('039 C Old City 1', '13')
filedata = filedata.replace('039 L Old City 1', '14')
filedata = filedata.replace('009 B Capitol Hill', '15')
filedata = filedata.replace('039 M Old City 1', '16')
filedata = filedata.replace('039 F Old City 1', '17')
filedata = filedata.replace('039 B Old City 1', '18')
filedata = filedata.replace('039 D Old City 1', '19')
filedata = filedata.replace('039 A Old City 1', '20')
filedata = filedata.replace('039 G Old City 1', '21')
filedata = filedata.replace('039 H Old City 1', '22')
filedata = filedata.replace('025 D Georgetown', '23')
filedata = filedata.replace('025 G Georgetown', '24')
filedata = filedata.replace('025 J Georgetown', '25')
filedata = filedata.replace('025 H Georgetown', '26')
filedata = filedata.replace('025 I Georgetown', '27')
filedata = filedata.replace('025 B Georgetown', '28')
filedata = filedata.replace('025 E Georgetown', '29')
filedata = filedata.replace('025 F Georgetown', '30')
filedata = filedata.replace('008 B Burleith', '31')
filedata = filedata.replace('008 A Burleith', '32')
filedata = filedata.replace('025 A Georgetown', '33')
filedata = filedata.replace('025 c Georgetown', '34')
filedata = filedata.replace('041 B Palisades', '35')
filedata = filedata.replace('004 A Berkley', '36')
filedata = filedata.replace('004 C Berkley', '37')
filedata = filedata.replace('030 C Kent', '38')
filedata = filedata.replace('004 B Berkley', '39')
filedata = filedata.replace('030 B Kent', '40')
filedata = filedata.replace('054 A Wesley Heights', '41')
filedata = filedata.replace('041 A Palisades', '42')
filedata = filedata.replace('001 B American University', '43')
filedata = filedata.replace('050 A Spring Valley', '44')
filedata = filedata.replace('001 C American University', '45')
filedata = filedata.replace('050 B Spring Valley', '46')
filedata = filedata.replace('030 A Kent', '47')
filedata = filedata.replace('050 D Spring Valley', '48')
filedata = filedata.replace('050 C Spring Valley', '49')
filedata = filedata.replace('054 B Wesley Heights', '50')
filedata = filedata.replace('001 A American University', '51')
filedata = filedata.replace('011 A Chevy Chase', '52')
filedata = filedata.replace('011 C Chevy Chase', '53')
filedata = filedata.replace('011 B Chevy Chase', '54')
filedata = filedata.replace('011 E Chevy Chase', '55')
filedata = filedata.replace('011 D Chevy Chase', '56')
filedata = filedata.replace('029 A Kalorama', '57')
filedata = filedata.replace('029 C Kalorama', '58')
filedata = filedata.replace('036 A Mt. Pleasant', '59')
filedata = filedata.replace('036 C Mt. Pleasant', '60')
filedata = filedata.replace('029 B Kalorama', '61')
filedata = filedata.replace('036 B Mt. Pleasant', '62')
filedata = filedata.replace('007 E Brookland', '63')
filedata = filedata.replace('015 A Columbia Heights', '64')
filedata = filedata.replace('015 B Columbia Heights', '65')
filedata = filedata.replace('049 A 16th Street Heights', '66')
filedata = filedata.replace('006 A Brightwood', '67')
filedata = filedata.replace('049 B 16th Street Heights', '68')
filedata = filedata.replace('015 D Columbia Heights', '69')
filedata = filedata.replace('015 E Columbia Heights', '70')
filedata = filedata.replace('049 C 16th Street Heights', '71')
filedata = filedata.replace('006 E Brightwood', '72')
filedata = filedata.replace('042 B Petworth', '73')
filedata = filedata.replace('006 C Brightwood', '74')
filedata = filedata.replace('006 B Brightwood', '75')
filedata = filedata.replace('006 D Brightwood', '76')
filedata = filedata.replace('015 C Columbia Heights', '77')
filedata = filedata.replace('031 A Ledroit Park', '78')
filedata = filedata.replace('042 A Petworth', '79')
filedata = filedata.replace('019 A Eckington', '80')
filedata = filedata.replace('031 B Ledroit Park', '81')
filedata = filedata.replace('042 C Petworth', '82')
filedata = filedata.replace('019 B Eckington', '83')
filedata = filedata.replace('007 A Brookland', '84')
filedata = filedata.replace('007 B Brookland', '85')
filedata = filedata.replace('007 C Brookland', '86')
filedata = filedata.replace('005 A Brentwood', '87')
filedata = filedata.replace('007 D Brookland', '88')
filedata = filedata.replace('052 A Trinidad', '89')
filedata = filedata.replace('052 B Trinidad', '90')
filedata = filedata.replace('005 B Brentwood', '91')
filedata = filedata.replace('056 C Woodridge', '92')
filedata = filedata.replace('056 A Woodridge', '93')
filedata = filedata.replace('056 B Woodridge', '94')
filedata = filedata.replace('052 C Trinidad', '95')
filedata = filedata.replace('056 D Woodridge', '96')
filedata = filedata.replace('032 B Lily Ponds', '97')
filedata = filedata.replace('018 A Deanwood', '98')
filedata = filedata.replace('032 A Lily Ponds', '99')
filedata = filedata.replace('018 E Deanwood', '100')
filedata = filedata.replace('018 B Deanwood', '101')
filedata = filedata.replace('018 C Deanwood', '102')
filedata = filedata.replace('033 A Marshall Heights', '103')
filedata = filedata.replace('018 D Deanwood', '104')
filedata = filedata.replace('033 B Marshall Heights', '105')
filedata = filedata.replace('022 C Fort Dupont Park', '106')
filedata = filedata.replace('022 D Fort Dupont Park', '107')
filedata = filedata.replace('028 A Hillcrest', '108')
filedata = filedata.replace('022 B Fort Dupont Park', '109')
filedata = filedata.replace('022 A Fort Dupont Park', '110')
filedata = filedata.replace('002 B Anacostia', '111')
filedata = filedata.replace('028 B Hillcrest', '112')
filedata = filedata.replace('043 A Randle Heights', '113')
filedata = filedata.replace('028 C Hillcrest', '114')
filedata = filedata.replace('043 B Randle Heights', '115')
filedata = filedata.replace('002 A Anacostia', '116')
filedata = filedata.replace('043 C Randle Heights', '117')
filedata = filedata.replace('043 D Randle Heights', '118')
filedata = filedata.replace('016 B Congress Heights', '119')
filedata = filedata.replace('016 C Congress Heights', '120')
filedata = filedata.replace('016 A Congress Heights', '121')



# Write the file out again
with open('assubnbhd.csv', 'w') as file:
  file.write(filedata)


